"""Explodable — live demo.

Showcases the content engine architecture, knowledge base, and sample
outputs. Connects to Supabase for live KB stats.
"""

import os
from pathlib import Path

import streamlit as st
import requests

# Load env
env_path = Path(__file__).resolve().parent.parent / ".env"
if env_path.exists():
    for line in open(env_path):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))

# Streamlit Cloud secrets
if hasattr(st, "secrets"):
    for k, v in st.secrets.items():
        os.environ.setdefault(k, str(v))


SUPA_URL = "https://cgausradwkpvdsiaarkj.supabase.co"
SUPA_KEY = os.environ.get("SUPABASE_SECRET_KEY", "")
SUPA_HEADERS = {"apikey": SUPA_KEY, "Authorization": f"Bearer {SUPA_KEY}"} if SUPA_KEY else {}


def supa_count(table: str, filters: str = "") -> int:
    if not SUPA_KEY:
        return 0
    try:
        r = requests.get(
            f"{SUPA_URL}/rest/v1/{table}?select=id&{filters}",
            headers={**SUPA_HEADERS, "Prefer": "count=exact"},
            timeout=10,
        )
        return int(r.headers.get("Content-Range", "0/0").split("/")[-1])
    except Exception:
        return 0


def supa_query(table: str, select: str = "*", filters: str = "", limit: int = 10) -> list:
    if not SUPA_KEY:
        return []
    try:
        r = requests.get(
            f"{SUPA_URL}/rest/v1/{table}?select={select}&{filters}&limit={limit}",
            headers=SUPA_HEADERS,
            timeout=10,
        )
        return r.json() if r.status_code == 200 else []
    except Exception:
        return []


# ── Page config ──

st.set_page_config(
    page_title="Explodable — AI Content Engine",
    page_icon="🔬",
    layout="wide",
)

# ── Sidebar ──

with st.sidebar:
    st.title("Explodable")
    st.caption("AI content engine for B2B buyer psychology")

    st.markdown("---")
    st.markdown("### Knowledge Base")

    n_findings = supa_count("findings", "status=eq.active")
    n_rels = supa_count("finding_relationships")

    if n_findings:
        st.metric("Active findings", n_findings)
        st.metric("Typed relationships", n_rels)
    else:
        st.metric("Active findings", 305)
        st.metric("Typed relationships", 763)

    st.metric("Root anxieties", 5)
    st.metric("Cultural domains", 24)

    st.markdown("---")
    st.markdown("### Pipeline architecture")
    st.markdown("""
    1. **Topic router** classifies topic
    2. **Retrieval** selects findings from KB
    3. **Graph expansion** adds cross-domain connections via PPR
    4. **Thesis outline** structures argument through fear→testimony
    5. **Draft** generates essay with inline citations
    6. **Adversarial critic** (Gemini Flash) identifies weaknesses
    7. **Revision gate** Pareto filter — improve without regressing
    8. **Judge** scores against calibrated 10-criterion rubric
    """)

    st.markdown("---")
    st.markdown("""
    **Built with:** Claude Sonnet 4, LangGraph, pgvector, igraph

    **Built through:** AI pair programming with Claude Code

    [GitHub repo](https://github.com/tjkuhns/explodable)
    """)

# ── Main area ──

st.title("Explodable")
st.markdown(
    "An AI content engine that produces analytical essays about B2B buyer psychology, "
    "grounded in a structured knowledge base of behavioral-science findings."
)

# ── Sample output ──

st.markdown("---")
st.markdown("## Sample output")
st.markdown("*Generated by the hybrid pipeline from KB findings on scarcity cognition, "
            "committee dynamics, and loss aversion:*")

st.markdown("""
> **The Mid-Market Trap**
>
> The VP of Operations at a \\$25M logistics company stares at three SaaS demos on her
> laptop at 4:47 PM on a Thursday. She's been in meetings since 7 AM, the CEO is asking
> for a vendor recommendation by Friday, and her team of eight stakeholders can't agree
> on basic requirements. She closes the laptop and defaults to "let's table this until Q2"
> — the same decision she made last quarter.
>
> The mid-market sits in a decision-making dead zone. Too big for intuitive founder choices.
> Too small for enterprise decision infrastructure. They don't decide with logic first,
> then hire fear to audit. **They decide with fear first, then hire logic to testify.**
""")

# ── Key findings ──

st.markdown("---")
st.markdown("## Key findings from the evaluation harness")

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Thesis outline effect", "+8 points",
              help="Encoding the thesis as a structural schema in the outline stage vs standard prompting. Validated at N=50.")
with col2:
    st.metric("Cross-domain improvement", "+13 points",
              help="Wiki index scan + graph expansion vs vector retrieval on topics requiring synthesis across unrelated fields.")
with col3:
    st.metric("Judge calibration", "ρ = 0.841",
              help="Spearman correlation against a 5-model editorial panel (Gemini, Grok, DeepSeek, Mistral, GPT-5).")

st.markdown("")

col4, col5, col6 = st.columns(3)
with col4:
    st.metric("CAG for generation", "Failed",
              help="Full-context stuffing (115K tokens) scored 26.3 vs 32.0 for focused approaches. Every published CAG evaluation is on QA tasks — this is a negative result on generation.")
with col5:
    st.metric("Validation topics", "N=50",
              help="Tested across dense, medium, sparse, cross-domain, and out-of-distribution conditions with confidence intervals.")
with col6:
    st.metric("Cost per draft", "$0.09",
              help="vs $0.30 for the monolithic retrieval pipeline. 3.3x cheaper with higher quality on cross-domain topics.")

# ── KB explorer ──

st.markdown("---")
st.markdown("## Knowledge base explorer")
st.markdown("Browse findings from the anxiety-indexed behavioral science knowledge base.")

anxiety_filter = st.selectbox(
    "Filter by root anxiety",
    ["All", "helplessness", "insignificance", "isolation", "meaninglessness", "mortality"]
)

if anxiety_filter == "All":
    findings = supa_query(
        "findings",
        select="claim,academic_discipline,confidence_score,root_anxieties,cultural_domains",
        filters="status=eq.active&order=confidence_score.desc",
        limit=20,
    )
else:
    findings = supa_query(
        "findings",
        select="claim,academic_discipline,confidence_score,root_anxieties,cultural_domains",
        filters=f"status=eq.active&root_anxieties=cs.{{{anxiety_filter}}}&order=confidence_score.desc",
        limit=20,
    )

if findings:
    for f in findings:
        with st.expander(f"**{f['claim'][:100]}{'...' if len(f['claim']) > 100 else ''}**"):
            st.markdown(f"**Full claim:** {f['claim']}")
            st.markdown(f"**Discipline:** {f['academic_discipline']}")
            st.markdown(f"**Confidence:** {f['confidence_score']:.2f}")
            st.markdown(f"**Anxieties:** {', '.join(f.get('root_anxieties', []))}")
            domains = f.get('cultural_domains', [])
            if domains:
                st.markdown(f"**Domains:** {', '.join(domains)}")
else:
    st.info("Connect to Supabase to browse findings. Set SUPABASE_SECRET_KEY in secrets.")

# ── Architecture detail ──

st.markdown("---")
st.markdown("## Architecture")

st.code("""
topic_router ─────── classifies topic, routes to optimal retrieval
  ├─ wiki_selector ── reads KB index, picks findings across domains
  ├─ vector_retriever ── pgvector similarity search within cluster
  └─ graph_walker ──── PPR traversal + MMR diversity reranking
         │
graph_expander ────── adds cross-domain findings via relationship graph
         │
outline_generator ─── thesis-constrained (Architecture B)
         │               each section must instantiate fear→testimony
         │
draft_generator ───── focused context, voice profile, citations
         │
adversarial_critic ── different model reads full KB + draft,
         │               finds weak claims, missing evidence
         │
revision_gate ─────── Pareto filter: accept only if quality improves
         │
quality_gate ──────── calibrated judge + execution gate
""", language=None)

st.markdown("---")
st.caption("Built by Tom Kuhns · Youngstown, OH · [GitHub](https://github.com/tjkuhns/explodable)")
